[package]
name = "day15-beacon-exclusion-zone"
version = "0.1.0"
edition = "2021"
default-run = "day15-beacon-exclusion-zone"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
colored = "2.0"
